version: '3.8'
services:
  
  db:
    container_name: 'sb_postgre'
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
  
  web:
    container_name: 'sb_app'
    build:
      context: .
      dockerfile: app.dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/setup &&./bin/dev"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRE_HOST: ${POSTGRE_HOST}
      POSTGRE_USER: ${POSTGRE_USER}
      POSTGRE_PASSWORD: ${POSTGRE_PASSWORD}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SEATS_IO_SECRET: ${SEATS_IO_SECRET}
      SEATS_IO_PUBLIC: ${SEATS_IO_PUBLIC}
      ABSTRACT_EMAIL_KEY: ${ABSTRACT_EMAIL_KEY}
      ABSTRACT_GEO_KEY: ${ABSTRACT_GEO_KEY}
    tty: true
    stdin_open: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge